name: Android CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'releases/**'

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Run Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: ./monkeylogin.sh